export type { Deal, DealStage } from '@/domain/deals/deal.types'
export type { Client, ClientType } from '@/domain/clients/client.types'
export type { Lead, LeadStatus } from '@/domain/leads/lead.types'
export type { Document, DocumentStatus } from '@/domain/documents/document.types'
export type { Activity, ActivityType } from '@/domain/activities/activity.types'
